import type { Hairstyle } from "./types";

/*
 * The style catalog: structured data the recommender and the image generator
 * both read from, never hardcoded in components. Millimetre values follow
 * standard clipper-guard conventions so the barber card can be executed
 * literally. hairTypes values must match the vision profile's texture enum.
 */
export const HAIRSTYLES: Hairstyle[] = [
  {
    id: "low-taper",
    name: "Low Taper",
    category: "taper",
    lengthClass: "corto",
    hasFade: true,
    cutTexture: "medium",
    volume: "medium",
    maintenance: "low-medium",
    hairTypes: ["liso", "ondulado", "rizado"],
    needsDensity: "baja",
    recommendedFaceShapes: ["oval", "rectangular", "square", "heart", "diamond"],
    vibes: ["modern", "casual", "professional"],
    barber: { top: "1.5 to 2.5 in", sides: "Low taper, #1 to #3", fade: "Low taper, sideburns and nape only", texture: "Medium", fringe: "Natural, forward", finish: "Natural matte" },
    gen: "a LOW TAPER haircut: top 4-6cm with natural texture, sides gradually tapered only around the sideburns and nape from 3mm to 9mm, clean neckline, natural front hairline, matte finish",
  },
  {
    id: "low-fade",
    name: "Low Fade",
    category: "fade",
    lengthClass: "corto",
    hasFade: true,
    cutTexture: "medium",
    volume: "medium",
    maintenance: "medium",
    hairTypes: ["liso", "ondulado", "rizado", "muy-rizado"],
    needsDensity: "baja",
    recommendedFaceShapes: ["oval", "rectangular", "square", "round"],
    vibes: ["modern", "casual", "youthful"],
    barber: { top: "1.5 to 2.75 in", sides: "Low fade, skin to #2", fade: "Low, just above the ear", texture: "Medium", fringe: "Light, forward", finish: "Natural" },
    gen: "a LOW FADE haircut: top 4-7cm, sides faded from 0.5mm just above the ear blending up to 6mm, smooth gradient, textured top pushed slightly forward",
  },
  {
    id: "mid-fade",
    name: "Mid Fade",
    category: "fade",
    lengthClass: "corto",
    hasFade: true,
    cutTexture: "medium",
    volume: "medium",
    maintenance: "medium",
    hairTypes: ["liso", "ondulado", "rizado", "muy-rizado"],
    needsDensity: "media",
    recommendedFaceShapes: ["oval", "round", "square", "heart"],
    vibes: ["modern", "youthful", "bold"],
    barber: { top: "1.5 to 2.75 in", sides: "Mid fade, skin to #2", fade: "Mid, at temple height", texture: "Medium to high", fringe: "Textured", finish: "Matte" },
    gen: "a MID FADE haircut: top 4-7cm with visible texture, sides faded to skin at temple height blending up to 6mm, sharp clean gradient",
  },
  {
    id: "high-fade",
    name: "High Fade",
    category: "fade",
    lengthClass: "corto",
    hasFade: true,
    cutTexture: "medium",
    volume: "high",
    maintenance: "medium",
    hairTypes: ["liso", "ondulado", "rizado", "muy-rizado"],
    needsDensity: "media",
    recommendedFaceShapes: ["oval", "round", "heart"],
    vibes: ["bold", "youthful", "modern"],
    barber: { top: "2 to 3 in", sides: "High fade to skin", fade: "High, two fingers above the ear", texture: "Medium", fringe: "None, worn up", finish: "To style" },
    gen: "a HIGH FADE haircut: top 5-8cm standing with volume, sides faded to skin high on the head two fingers above the ear, dramatic contrast",
  },
  {
    id: "skin-fade",
    name: "Skin Fade",
    category: "fade",
    lengthClass: "muy-corto",
    hasFade: true,
    cutTexture: "low",
    volume: "low",
    maintenance: "high",
    hairTypes: ["liso", "ondulado", "rizado", "muy-rizado"],
    needsDensity: "baja",
    recommendedFaceShapes: ["oval", "square", "diamond"],
    vibes: ["bold", "modern", "youthful"],
    barber: { top: "0.75 to 1.5 in", sides: "Razored to skin, up to #1", fade: "Razor finish, short transition", texture: "Low", fringe: "Minimal", finish: "Clean, sharp lines" },
    gen: "a SKIN FADE haircut: short top 2-4cm, sides shaved to bare skin with a razor blending quickly into 3mm, ultra clean sharp lines",
  },
  {
    id: "buzz-cut",
    name: "Buzz Cut",
    category: "clipper",
    lengthClass: "muy-corto",
    hasFade: false,
    cutTexture: "low",
    volume: "low",
    maintenance: "low",
    hairTypes: ["liso", "ondulado", "rizado", "muy-rizado"],
    needsDensity: "baja",
    recommendedFaceShapes: ["oval", "square", "diamond"],
    vibes: ["casual", "bold", "professional"],
    barber: { top: "#1 to #2 all over", sides: "Same guard or one lower", fade: "Optional nape taper", texture: "None", fringe: "None", finish: "No product" },
    gen: "a BUZZ CUT: uniform 3-6mm clipper length all over the head, soft natural hairline, optional slight taper at the nape",
  },
  {
    id: "crew-cut",
    name: "Crew Cut",
    category: "clipper",
    lengthClass: "muy-corto",
    hasFade: true,
    cutTexture: "low",
    volume: "low",
    maintenance: "low",
    hairTypes: ["liso", "ondulado", "rizado"],
    needsDensity: "baja",
    recommendedFaceShapes: ["oval", "rectangular", "square"],
    vibes: ["classic", "professional", "casual"],
    barber: { top: "0.5 to 1.25 in", sides: "#1 blending to #2", fade: "Low taper", texture: "Low", fringe: "Short, straight", finish: "No product" },
    gen: "a CREW CUT: top 1.5-3cm slightly longer at the front hairline, sides tapered 1.5mm to 6mm with a low taper, clean military look",
  },
  {
    id: "french-crop",
    name: "French Crop",
    category: "crop",
    lengthClass: "corto",
    hasFade: true,
    cutTexture: "medium",
    volume: "low",
    maintenance: "low-medium",
    hairTypes: ["liso", "ondulado"],
    needsDensity: "media",
    recommendedFaceShapes: ["oval", "rectangular", "heart", "triangular"],
    vibes: ["modern", "casual", "youthful"],
    barber: { top: "1.25 to 2 in", sides: "Low or mid fade", fade: "Low to mid", texture: "Medium", fringe: "Straight, blunt, across the forehead", finish: "Matte" },
    gen: "a FRENCH CROP haircut: top 3-5cm combed forward into a straight compact blunt fringe across the forehead, low fade on the sides, matte texture",
  },
  {
    id: "textured-crop-low-taper",
    name: "Textured Crop and Low Taper",
    category: "crop",
    lengthClass: "corto",
    hasFade: true,
    cutTexture: "high",
    volume: "medium",
    maintenance: "low-medium",
    hairTypes: ["liso", "ondulado"],
    needsDensity: "alta",
    recommendedFaceShapes: ["oval", "square", "rectangular"],
    vibes: ["modern", "youthful", "casual"],
    barber: { top: "2 to 2.75 in", sides: "Short, low taper", fade: "Low taper", texture: "High, point cut", fringe: "Short and textured", finish: "Matte, clay or powder" },
    gen: "a TEXTURED CROP with a LOW TAPER: top 5-7cm heavily point-cut for choppy texture, short textured fringe, sides short with a clean low taper, controlled volume, matte finish",
  },
  {
    id: "caesar",
    name: "Caesar",
    category: "crop",
    lengthClass: "corto",
    hasFade: false,
    cutTexture: "low",
    volume: "low",
    maintenance: "low",
    hairTypes: ["liso", "ondulado", "rizado"],
    needsDensity: "media",
    recommendedFaceShapes: ["oval", "rectangular", "heart"],
    vibes: ["classic", "casual"],
    barber: { top: "0.75 to 1.5 in, even", sides: "Same length or soft taper", fade: "No hard fade", texture: "Low", fringe: "Straight, short, horizontal", finish: "Natural" },
    gen: "a CAESAR haircut: uniform 2-4cm all over combed forward, short straight horizontal fringe, soft taper on the sides, roman style",
  },
  {
    id: "textured-fringe",
    name: "Textured Fringe",
    category: "fringe",
    lengthClass: "medio",
    hasFade: true,
    cutTexture: "high",
    volume: "medium",
    maintenance: "medium",
    hairTypes: ["liso", "ondulado", "rizado"],
    needsDensity: "alta",
    recommendedFaceShapes: ["oval", "rectangular", "triangular"],
    vibes: ["youthful", "modern", "bold"],
    barber: { top: "2.5 to 3.5 in at the front", sides: "Mid fade", fade: "Mid", texture: "High", fringe: "Long, textured, forward", finish: "Flexible matte" },
    gen: "a TEXTURED FRINGE haircut: top 6-9cm longest at the front falling forward as a heavy textured fringe over the forehead, mid fade sides, piecey separated strands",
  },
  {
    id: "side-part",
    name: "Side Part",
    category: "classic",
    lengthClass: "medio",
    hasFade: false,
    cutTexture: "low",
    volume: "medium",
    maintenance: "medium",
    hairTypes: ["liso", "ondulado"],
    needsDensity: "media",
    recommendedFaceShapes: ["oval", "round", "square"],
    vibes: ["classic", "elegant", "professional"],
    barber: { top: "2 to 3 in", sides: "Scissor work or classic taper", fade: "None or soft taper", texture: "Low, combed", fringe: "Combed to the side", finish: "Light shine" },
    gen: "a classic SIDE PART haircut: top 5-8cm combed cleanly to one side with a defined parting line, scissor-cut sides with a soft classic taper, light shine finish",
  },
  {
    id: "classic-taper",
    name: "Classic Taper",
    category: "classic",
    lengthClass: "corto",
    hasFade: true,
    cutTexture: "low",
    volume: "low",
    maintenance: "low-medium",
    hairTypes: ["liso", "ondulado", "rizado"],
    needsDensity: "baja",
    recommendedFaceShapes: ["oval", "rectangular", "square", "round", "heart", "diamond", "triangular"],
    vibes: ["classic", "professional", "elegant"],
    barber: { top: "1.5 to 2.5 in", sides: "Scissor over comb, tapered", fade: "Gradual classic taper", texture: "Low", fringe: "Natural", finish: "Natural" },
    gen: "a CLASSIC TAPER haircut: top 4-6cm neatly styled, sides scissor-over-comb gradually tapering down to the hairline, timeless barbershop cut, natural finish",
  },
  {
    id: "slick-back",
    name: "Slick Back",
    category: "classic",
    lengthClass: "medio",
    hasFade: false,
    cutTexture: "low",
    volume: "medium",
    maintenance: "medium",
    hairTypes: ["liso", "ondulado"],
    needsDensity: "media",
    recommendedFaceShapes: ["oval", "round", "heart"],
    vibes: ["elegant", "classic", "professional"],
    barber: { top: "3 to 4.5 in", sides: "Short and clean, optional taper", fade: "Optional taper", texture: "Low", fringe: "None, all back", finish: "Pomade, medium shine" },
    gen: "a SLICK BACK haircut: top 8-12cm combed straight back with pomade, medium shine, sides shorter and clean, no parting, elegant gangster style",
  },
  {
    id: "quiff",
    name: "Quiff",
    category: "volume",
    lengthClass: "medio",
    hasFade: true,
    cutTexture: "medium",
    volume: "high",
    maintenance: "medium",
    hairTypes: ["liso", "ondulado"],
    needsDensity: "alta",
    recommendedFaceShapes: ["oval", "round", "square"],
    vibes: ["modern", "elegant", "bold"],
    barber: { top: "2.75 to 4 in at the front", sides: "Low fade or taper", fade: "Low", texture: "Medium", fringe: "Lifted up and back", finish: "Volume, matte or soft shine" },
    gen: "a QUIFF haircut: top 7-10cm longest at the front styled upward and back with volume, low fade sides, voluminous front sweep",
  },
  {
    id: "pompadour",
    name: "Pompadour",
    category: "volume",
    lengthClass: "medio",
    hasFade: true,
    cutTexture: "low",
    volume: "high",
    maintenance: "high",
    hairTypes: ["liso", "ondulado"],
    needsDensity: "alta",
    recommendedFaceShapes: ["oval", "round"],
    vibes: ["elegant", "bold", "classic"],
    barber: { top: "3.5 to 5 in at the front", sides: "Tight fade or taper", fade: "Low to mid", texture: "Low, combed", fringe: "None, large volume back", finish: "Pomade, shine" },
    gen: "a POMPADOUR haircut: top 9-13cm swept up and back into a large rounded volume at the front, glossy pomade finish, tight faded sides, rockabilly elegance",
  },
  {
    id: "ivy-league",
    name: "Ivy League",
    category: "classic",
    lengthClass: "corto",
    hasFade: false,
    cutTexture: "low",
    volume: "low",
    maintenance: "low-medium",
    hairTypes: ["liso", "ondulado"],
    needsDensity: "media",
    recommendedFaceShapes: ["oval", "rectangular", "square", "heart"],
    vibes: ["professional", "classic", "elegant"],
    barber: { top: "1.25 to 2 in", sides: "Scissored, soft taper", fade: "None", texture: "Low", fringe: "Combed to the side, short", finish: "Natural or minimal shine" },
    gen: "an IVY LEAGUE haircut: top 3-5cm long enough to part and comb to the side, scissor-tapered sides, preppy professional look, natural finish",
  },
  {
    id: "undercut",
    name: "Undercut",
    category: "contrast",
    lengthClass: "medio",
    hasFade: false,
    cutTexture: "medium",
    volume: "medium",
    maintenance: "medium",
    hairTypes: ["liso", "ondulado", "rizado"],
    needsDensity: "alta",
    recommendedFaceShapes: ["oval", "square", "diamond"],
    vibes: ["bold", "modern", "youthful"],
    barber: { top: "3 to 4.5 in", sides: "#1 to #2, no blend", fade: "None, disconnected", texture: "Medium", fringe: "To style", finish: "To style" },
    gen: "an UNDERCUT haircut: top 8-12cm clearly disconnected from the sides, sides clipped to 3-6mm with NO blend or gradient, sharp contrast line",
  },
  {
    id: "bro-flow",
    name: "Bro Flow",
    category: "long",
    lengthClass: "largo",
    hasFade: false,
    cutTexture: "medium",
    volume: "high",
    maintenance: "low",
    hairTypes: ["liso", "ondulado", "rizado"],
    needsDensity: "media",
    recommendedFaceShapes: ["oval", "rectangular", "triangular"],
    vibes: ["casual", "bold", "youthful"],
    barber: { top: "5 to 8 in", sides: "Long, layered", fade: "None", texture: "Medium, layers", fringe: "Swept back, natural fall", finish: "Natural, airy" },
    gen: "a BRO FLOW haircut: medium-long hair 12-20cm flowing back and to the sides with natural movement, layered, relaxed surfer look, no fade",
  },
  {
    id: "messy-crop",
    name: "Messy Crop",
    category: "crop",
    lengthClass: "corto",
    hasFade: true,
    cutTexture: "high",
    volume: "medium",
    maintenance: "low",
    hairTypes: ["liso", "ondulado", "rizado"],
    needsDensity: "media",
    recommendedFaceShapes: ["oval", "rectangular", "square", "round", "heart", "diamond", "triangular"],
    vibes: ["casual", "youthful", "modern"],
    barber: { top: "1.5 to 2.5 in", sides: "Low taper", fade: "Low, soft", texture: "Very high, deliberately messy", fringe: "Irregular, tousled", finish: "Matte, styled with fingers" },
    gen: "a MESSY CROP haircut: top 4-6cm cut with heavy choppy texture styled deliberately messy with fingers, irregular textured fringe, soft low taper sides, matte",
  },
];

export const styleById = (id: string) => HAIRSTYLES.find((s) => s.id === id);
